version: '3.9'

networks:
  muroknet:
    external: true

services:
  db:
    image: mariadb:lts
    volumes:
      - db_data:/var/lib/mariadb/data
    environment:
      MARIADB_USER: run/secrets/mariadb_user
      MARIADB_DATABASE: run/secrets/mariadb_database
      MARIADB_PASSWORD: run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD: run/secrets/mariadb_root_password
    secrets:
      - mariadb_user
      - mariadb_database
      - mariadb_password
      - mariadb_root_password
    networks:
      - muroknet
  murok:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: runner
    image: capella87/murok:latest
    # You can override the command by docker-compose run murok python manage.py makemigrations
    # This command does not use QUIC currently because of the certificate issue
    command: /bin/sh -c "./entrypoint.sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - muroknet
    depends_on:
      - db
    volumes:
      - .:/app:/usr/src/app
      - static:/usr/src/app/static
    environment:
      IS_DOCKERIZED: 1
      DJANGO_SUPERUSER_PASSWORD: run/secrets/django_superuser_password
      DJANGO_SUPERUSER_EMAIL: run/secrets/django_superuser_email
      DJANGO_SUPERUSER_USERNAME: run/secrets/django_superuser_username
    secrets:
      - secret_keys
      - dbconnection
      - django_superuser_password
      - django_superuser_email
      - django_superuser_username
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M
  traefik_whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.loadbalancer.server.port=80"
    networks:
      - muroknet
  traefik_reverse_proxy:
    image: traefik:v3.0.0-beta4 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - traefik_log:/var/log
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "8000:8888"
      - "8080:8080"
    networks:
      - muroknet
    environment:
      DUCKDNS_TOKEN: run/secrets/duckdns_token
    secrets:
      - duckdns_token
    configs:
      - source: traefikconfig
        target: /etc/traefuk/traefik.yml
    deploy:
      placement:
        constraints:
        #  - node.labels.muroknet.murok-certificates == true
          - node.role == manager
          
      # Dynamic Configurations
      labels:
        - traefik.enable=true
        - traefik.docker.network=muroknet
        - traefik.constraint-label=muroknet
        - traefik.http.middlewares.admin-auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_HASHED_PASSWORD}
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.muroknet-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.muroknet-http.entrypoints=http
        - traefik.http.routers.muroknet-http.middlewares=https-redirect

        - traefik.http.routers.muroknet-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.muroknet-https.entrypoints=https
        - traefik.http.routers.muroknet-https.tls=true
        - traefik.http.routers.muroknet-https.service=api@internal
        - traefik.http.routers.muroknet-https.tls.certresolver=letsencrypt
        - traefik.http.routers.muroknet-https.middlewares=admin-auth
        - traefik.http.services.muroknet.loadbalancer.server.port=8000
secrets:
  secret_keys:
    file: ./secrets.json
    external: true
  dbconnection:
    file: ./dbconnection.cnf
    external: true

  mariadb_user:
    external: true
  mariadb_database:
    external: true
  mariadb_password:
    external: true
  mariadb_root_password:
    external: true

  django_superuser_password:
    external: true
  django_superuser_email:
    external: true
  django_superuser_username:
    external: true

  duckdns_token:
    external: true


volumes:
  db_data:
  static:
  letsencrypt:
  traefik_log:

configs:
  traefikconfig:
    file: ./traefik.yml